---
- name: Install Deep Security Agent
  hosts: tag_Name_TechDay_Database, tag_Name_TechDay_Reverse_Proxy, tag_Name_TechDay_Webserver
  roles:
    - role: deep-security.deep-security-agent
      operation: deploy
      #DSaaS
      tenant_id: "{{ ds_tenant_id }}"
      tenant_password: "{{ ds_tenant_password }}"
      token: "{{ ds_token }}"
      force_reactivation: true
      policy_name: "TechDay - general"
#      policy_name: "Base Policy"



       #DS on premise
#      dsm_agent_download_hostname: dsm.ceur-testlab.trendmicro.de
#      dsm_agent_download_port: 4119
#      dsm_agent_activation_hostname: dsm.ceur-testlab.trendmicro.de
#      dsm_agent_activation_port: 4120
