---

- name: Install software on DB Servers
  hosts: tag_Name_AnsibleDemo_Database

  pre_tasks:
    - name: Update repositories cache if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install the latest version of "postgresql"
      apt:
        name: postgresql
        state: present

  roles:
    - role: deep-security.deep-security-agent
      operation: set-policy-by-name
      policy_name: "AnsibleDemo - Database"

    - role: deep-security.deep-security-agent
      operation: update-configuration

    - role: deep-security.deep-security-agent
      operation: run-recommendation-scans

- name: Install software on Web Servers
  hosts: tag_Name_AnsibleDemo_Webserver

  pre_tasks:
    - name: Update repositories cache if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install the latest version of "apache2"
      apt:
        name: apache2
        state: present

  roles:
    - role: deep-security.deep-security-agent
      operation: set-policy-by-id
      policy_id: 603

    - role: deep-security.deep-security-agent
      operation: update-configuration

    - role: deep-security.deep-security-agent
      operation: run-recommendation-scans

- name: Install software on reverse proxys
  hosts: tag_Name_AnsibleDemo_Reverse_Proxy

  pre_tasks:
    - name: Update repositories cache if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install the latest version of "nginx"
      apt:
        name: nginx
        state: present

  roles:
    - role: deep-security.deep-security-agent
      policy_name: AnsibleDemo - Reverse Proxy
      operation: set-policy-by-name

    - role: deep-security.deep-security-agent
      operation: update-configuration

    - role: deep-security.deep-security-agent
      operation: run-recommendation-scans
